services:
  app:
    build: .
    image: data-jobs-in-indonesia:0.2
    container_name: data-jobs-in-indonesia
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}