name: schedule-py-script-weekly

on:
  # schedule:
  #   - cron: '0 0 * * 0' # At 00:00 on Sunday
  workflow_dispatch

jobs:
  run-py-script:
    runs-on: ubuntu-latest
    environment: Secret Variables
    steps:
          
      - name: Check out repository
        uses: actions/checkout@v3 # checkout the repository content to github runner
          
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          rm google-chrome-stable_current_amd64.deb
          sudo apt-get clean

      - name: Execute py script
        run: |
          python src/main.py